# Generated by Django 3.1 on 2020-08-21 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 6, 2, 6, 286187, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
