# Generated by Django 3.1 on 2020-08-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_admin', '0002_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
