# Generated by Django 3.1 on 2020-08-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_admin', '0004_auto_20200821_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='savings_plan',
            field=models.CharField(choices=[('wp', 'Weekly Plan'), ('mp', 'Monthly Plan'), ('yp', 'Yearly Plan')], default='wp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
